### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by JayBizzle** [vially/cpanel-lib#3]
Any chance of tagging a new release as it wasn't immediately obvious when I installed that I wasn't getting the latest version.

Adding `"cpanel-lib": "git://github.com/vially/cpanel-lib.git#master"` to my `package.json` fixed the problem, but it would be nice for a proper tagged release.

Thanks

**Comment by vially** [comment]
Sure. I just pushed version 0.0.4 on npm, but please keep in mind that I haven't touched this package in a very long time and I have no idea if it still works as advertised.

Cheers!

**Comment by JayBizzle** [comment]
Brilliant thanks.

Everything seems to be working as expected, although

**Comment by vially** [comment]
Awesome. Good luck with your app!
